# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    view:
      view_response_listener:  true
    exception:
        exception_controller: 'fos_rest.exception.controller:showAction'
        codes:
          Doctrine\ORM\EntityNotFoundException: 404
          \LogicException: 400
          \DomainException: 400
        messages:
          Doctrine\ORM\EntityNotFoundException: true
          \LogicException: true
          \DomainException: true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations
    format_listener:
      rules:
        - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json ] }